/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CommandService } from "../command.service";
import { CommandCreateInput } from "./CommandCreateInput";
import { Command } from "./Command";
import { CommandFindManyArgs } from "./CommandFindManyArgs";
import { CommandWhereUniqueInput } from "./CommandWhereUniqueInput";
import { CommandUpdateInput } from "./CommandUpdateInput";
import { TimerFindManyArgs } from "../../timer/base/TimerFindManyArgs";
import { Timer } from "../../timer/base/Timer";
import { TimerWhereUniqueInput } from "../../timer/base/TimerWhereUniqueInput";

export class CommandControllerBase {
  constructor(protected readonly service: CommandService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Command })
  async createCommand(
    @common.Body() data: CommandCreateInput
  ): Promise<Command> {
    return await this.service.createCommand({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        code: true,
        description: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Command] })
  @ApiNestedQuery(CommandFindManyArgs)
  async commands(@common.Req() request: Request): Promise<Command[]> {
    const args = plainToClass(CommandFindManyArgs, request.query);
    return this.service.commands({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        code: true,
        description: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Command })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async command(
    @common.Param() params: CommandWhereUniqueInput
  ): Promise<Command | null> {
    const result = await this.service.command({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        code: true,
        description: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Command })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCommand(
    @common.Param() params: CommandWhereUniqueInput,
    @common.Body() data: CommandUpdateInput
  ): Promise<Command | null> {
    try {
      return await this.service.updateCommand({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          code: true,
          description: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Command })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCommand(
    @common.Param() params: CommandWhereUniqueInput
  ): Promise<Command | null> {
    try {
      return await this.service.deleteCommand({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          code: true,
          description: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/timers")
  @ApiNestedQuery(TimerFindManyArgs)
  async findTimers(
    @common.Req() request: Request,
    @common.Param() params: CommandWhereUniqueInput
  ): Promise<Timer[]> {
    const query = plainToClass(TimerFindManyArgs, request.query);
    const results = await this.service.findTimers(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        interval: true,

        command: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/timers")
  async connectTimers(
    @common.Param() params: CommandWhereUniqueInput,
    @common.Body() body: TimerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      timers: {
        connect: body,
      },
    };
    await this.service.updateCommand({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/timers")
  async updateTimers(
    @common.Param() params: CommandWhereUniqueInput,
    @common.Body() body: TimerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      timers: {
        set: body,
      },
    };
    await this.service.updateCommand({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/timers")
  async disconnectTimers(
    @common.Param() params: CommandWhereUniqueInput,
    @common.Body() body: TimerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      timers: {
        disconnect: body,
      },
    };
    await this.service.updateCommand({
      where: params,
      data,
      select: { id: true },
    });
  }
}
