/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, VoltageReading as PrismaVoltageReading } from "@prisma/client";
import { VoltageReadingDto } from "../VoltageReadingDto";

export class VoltageReadingServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.VoltageReadingCountArgs, "select">
  ): Promise<number> {
    return this.prisma.voltageReading.count(args);
  }

  async voltageReadings(
    args: Prisma.VoltageReadingFindManyArgs
  ): Promise<PrismaVoltageReading[]> {
    return this.prisma.voltageReading.findMany(args);
  }
  async voltageReading(
    args: Prisma.VoltageReadingFindUniqueArgs
  ): Promise<PrismaVoltageReading | null> {
    return this.prisma.voltageReading.findUnique(args);
  }
  async createVoltageReading(
    args: Prisma.VoltageReadingCreateArgs
  ): Promise<PrismaVoltageReading> {
    return this.prisma.voltageReading.create(args);
  }
  async updateVoltageReading(
    args: Prisma.VoltageReadingUpdateArgs
  ): Promise<PrismaVoltageReading> {
    return this.prisma.voltageReading.update(args);
  }
  async deleteVoltageReading(
    args: Prisma.VoltageReadingDeleteArgs
  ): Promise<PrismaVoltageReading> {
    return this.prisma.voltageReading.delete(args);
  }
  async AddVoltageReading(args: VoltageReadingDto): Promise<VoltageReadingDto> {
    throw new Error("Not implemented");
  }
  async GetVoltageReadings(args: string): Promise<VoltageReadingDto[]> {
    throw new Error("Not implemented");
  }
}
